FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

RUN curl -fsSL https://go.speakeasy.com/cli-install.sh | sh

RUN go install github.com/google/gnostic@latest
RUN go install github.com/googleapis/gnostic-grpc@latest
RUN go install github.com/golang/protobuf/protoc-gen-go@latest
RUN go install github.com/bufbuild/buf/cmd/buf@v1.30.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

COPY . /app
WORKDIR /app

RUN go mod tidy

EXPOSE 50051
EXPOSE 8080

CMD ["go", "run", "main.go"]
